### ISSUE TITLE
Find the "elemental score" of a given word ...

### ISSUE THREAD

**Issue by kedarmhaswade** [vapporwashmade/java-projects#11]
Here is a [list](https://gist.github.com/kedarmhaswade/ca46b689652b98e0bbdb995e1dd615ec) of the [118 elements](https://gist.github.com/kedarmhaswade/ca46b689652b98e0bbdb995e1dd615ec) of the modern periodic table.

Given an English word, return its _elemental score_ based on this list. A word is said to have an elemental score if it can be expressed as a concatenation of symbols of the elements (we ignore the case of the letters in the symbols). Its elemental score then is the sum of the atomic numbers of those elements. For example, Salute (= SAlUTe=S + Al + U + Te) has an elemental score 16 + 13 + 92 + 52 = 173. If a word has more than one elemental score, you should return all the elemental scores. If there is no such concatenation, return -1; this implies that the word (e.g. "King") has no elemental score.

**Comment by vapporwashmade** [comment]
https://github.com/vapporwashmade/java-projects/blob/master/src/main/java/org/apoorv/progfun/ElementalScore.java
