### ISSUE TITLE
Improve toBase10Int method

### ISSUE THREAD

**Issue by kedarmhaswade** [vapporwashmade/java-projects#3]
Look at the [method: toBase10Int](https://github.com/vapporwashmade/java-projects/blob/4de4ac8024c686599f2f3c6a543d94a30473b78e/src/main/java/org/apoorv/progfun/NumArrayProblems.java#L99). You are using the `Math.pow` method. Change the implementation to _not_ use `Math.pow`. 

Hint: You are already calculating partial powers when calling the method `Math.pow(10, i)`.

**Comment by vapporwashmade** [comment]
Changed it.
