### ISSUE TITLE
Fibonacci Fun

### ISSUE THREAD

**Issue by kedarmhaswade** [vapporwashmade/java-projects#9]
I found this problem on UKMT.

> Find a set of Fibonacci numbers that among them contain each of the ten digits [0-9] exactly once.

Please update this issue if the problem is not clear.

First (try to) solve it with without writing a program. Then you should write a program to solve it.

**Comment by vapporwashmade** [comment]
[Solved](https://github.com/vapporwashmade/java-projects/blob/master/src/main/java/org/apoorv/progfun/FibonacciFun.java)
